name: Simple CI

on:
  push:
    tags:
      - 'c*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a simple command
        run: echo "Hello, world!"
